FROM alpine:latest AS builder
WORKDIR /
RUN apk update && apk add --no-cache curl jq unzip bash
COPY ./install/docker/docker_helper.sh ./docker_helper.sh
COPY ./install/docker/iptables.sh ./iptables.sh
COPY ./install/docker/ip6tables.sh ./ip6tables.sh
RUN sh -c "$(cat ./docker_helper.sh)"
RUN rm ./docker_helper.sh
EXPOSE 2017
VOLUME /etc/v2raya
ENTRYPOINT ["v2raya"]
